# Server Configuration
server.port=8001

# Application Name
spring.application.name=rabbitmq-backend

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Redis Configuration
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

# Redis Service URL
redis.service.url=${REDIS_SERVICE_URL:http://localhost:1222/redis}

# Eureka Configuration
eureka.instance.appname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_HOST:localhost}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.registry-fetch-interval-seconds=5

# Logging
logging.level.com.ksapp.rabbitmqdemo=INFO
